server:
  port: 8082

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

spring:
  applications:
    name: user-service

jwt:
  accessTokenSecret: _@tos2022
  refreshTokenSecret: _!-@tos2022
  accessTokenExpirationMinutes: 5
  refreshTokenExpirationDays: 30
